# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixitMain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=6, verbose_name=b'Tradesman ID')),
                ('address', models.CharField(max_length=125, verbose_name=b'Contact Adress')),
                ('city', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('passport', models.ImageField(blank=True, null=True, upload_to=b'Tradesmen passports', verbose_name=b'Tradesman passport')),
                ('tradesman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoporateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=b'Tradesmen_Logo', verbose_name=b'Coporate Logo')),
                ('verification_code', models.CharField(max_length=11, verbose_name=b'verification_colour')),
                ('rating', models.CharField(max_length=5, verbose_name=b'Agregate Rating')),
                ('jobs_count', models.CharField(max_length=6, verbose_name=b'Total jobs executed')),
                ('is_verified', models.BooleanField(default=False)),
                ('subscription_type', models.CharField(max_length=25)),
                ('sales_pitch', models.TextField(help_text=b'Briefly describe what you do', max_length=300)),
                ('company_name', models.CharField(max_length=75)),
                ('name_slug', models.SlugField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixitMain.JobCategories', verbose_name=b'Job specialization')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixitMain.SubCategories', verbose_name=b'Sub specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fixitTradesmen.Biodata', verbose_name=b'For ')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.ImageField(help_text=b'Drivers licence or international passport', max_length=125, upload_to=b'', verbose_name=b'Authorized Identity')),
                ('bank_slip', models.ImageField(blank=True, help_text=b'For name reconciliation purposes only', max_length=125, null=True, upload_to=b'', verbose_name=b'Bank slip')),
                ('utility_bill', models.FileField(blank=True, help_text=b'For address reconciliation purposes only', max_length=125, null=True, upload_to=b'')),
                ('certificate', models.FileField(blank=True, help_text=b'For address reconciliation purposes only', max_length=125, null=True, upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fixitTradesmen.Biodata', verbose_name=b'For ')),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_closed', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(default=0, max_length=4, verbose_name=b'Customer rating for this job')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=15)),
                ('fee', models.CharField(max_length=10)),
                ('review', models.TextField(blank=True, max_length=300, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixitMain.PostedJob', verbose_name=b'Job responded to')),
                ('tradesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixitTradesmen.CoporateData', verbose_name=b'Job Executed by')),
            ],
        ),
        migrations.CreateModel(
            name='Tradesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=75)),
                ('company_name_slug', models.SlugField(max_length=100)),
                ('sales_pitch', models.TextField(help_text=b'Briefly describe what you do', max_length=300)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=b'Tradesmen_Logo', verbose_name=b'Coporate Logo')),
                ('subscription_type', models.CharField(choices=[(b'Regular', b'Regular'), (b'PAYE', b'PAYE')], max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(max_length=11, verbose_name=b'verification_colour')),
                ('rating', models.CharField(default=0, max_length=5, verbose_name=b'Aggregate Rating')),
                ('jobs_count', models.CharField(default=0, max_length=6, verbose_name=b'Total jobs executed')),
                ('address', models.CharField(max_length=125, verbose_name=b'Contact Adress')),
                ('city', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('LGA', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('passport', models.ImageField(blank=True, null=True, upload_to=b'T-passports', verbose_name=b'Tradesman passport')),
                ('licence', models.ImageField(blank=True, help_text=b'Drivers licence or international passport', null=True, upload_to=b'T-Documents')),
                ('bank_slip', models.ImageField(blank=True, help_text=b'For name reconciliation purposes only', null=True, upload_to=b'T-Documents')),
                ('utility_bill', models.FileField(blank=True, help_text=b'For address reconciliation purposes only', null=True, upload_to=b'T-Documents')),
                ('certificate', models.FileField(blank=True, help_text=b'For address reconciliation purposes only', null=True, upload_to=b'T-Documents')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixitMain.JobCategories', verbose_name=b'Job specialization')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixitMain.SubCategories', verbose_name=b'Sub specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
