# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixitTradesmen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesman',
            name='userID',
            field=models.CharField(default='', max_length=6, verbose_name=b'Tradesman ID'),
            preserve_default=False,
        ),
    ]
