# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixitCustomers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='reg_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
